package ludo.view;
import java.io.File;
import ludo.controller.GameController;
import ludo.socket.*;

import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {
    // MainWindow acumula funções, mas ok
    private GameController gameController = new GameController();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        // Set title
        setTitle("Ludo dos campeões");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Carrega imagem
        File img = new File("img/ludo.png");
        boardPanel = new BoardView(img);
        diceLabel = new DiceView();
        rollButton = new javax.swing.JButton();
        historicoScrollPane = new javax.swing.JScrollPane();
        historicoPane = new javax.swing.JTextPane();
        historicoLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        conexMenu = new javax.swing.JMenu();
        serHostMenuItem = new javax.swing.JMenuItem();
        conectarMenuItem = new javax.swing.JMenuItem();
        ajudaMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boardPanel.setBackground(new java.awt.Color(255, 51, 204));
        boardPanel.setAlignmentX(0.0F);
        boardPanel.setAlignmentY(0.0F);
        boardPanel.setEnabled(false);
        boardPanel.setMinimumSize(new java.awt.Dimension(705, 705));
        boardPanel.setPreferredSize(new java.awt.Dimension(705, 705));
        boardPanel.setRequestFocusEnabled(false);
        boardPanel.setLayout(new java.awt.GridLayout(15, 15));

        rollButton.setText("Rolar dado");
        rollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollButtonActionPerformed(evt);
            }
        });

        historicoPane.setEditable(false);
        historicoPane.setFocusable(false);
        historicoScrollPane.setViewportView(historicoPane);

        historicoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        historicoLabel.setLabelFor(historicoPane);
        historicoLabel.setText("Histórico da partida");

        conexMenu.setText("Conexão");

        serHostMenuItem.setText("Ser host");
        serHostMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serHostMenuItemActionPerformed(evt);
            }
        });
        conexMenu.add(serHostMenuItem);

        conectarMenuItem.setText("Conectar");
        conexMenu.add(conectarMenuItem);

        jMenuBar1.add(conexMenu);

        ajudaMenu.setText("Ajuda");

        sobreMenuItem.setText("Sobre");
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        ajudaMenu.add(sobreMenuItem);

        jMenuBar1.add(ajudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(diceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(historicoLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rollButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(historicoScrollPane)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(rollButton)
                        .addGap(20, 20, 20)
                        .addComponent(historicoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historicoScrollPane))
                    .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollButtonActionPerformed
        int result = gameController.rollDice();
        // call setValue from DiceView
        DiceView diceView = (DiceView) diceLabel;
        diceView.setValue(result);
    }//GEN-LAST:event_rollButtonActionPerformed

    private void serHostMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serHostMenuItemActionPerformed
        // TODO add your handling code here:
        String localIP;
        localIP = Server.getNetworkIP();
        StringBuilder sb = new StringBuilder();
        sb.append("Seu IP local é: ");
        sb.append(localIP);
        JOptionPane.showMessageDialog(this, sb.toString(), "Seu IP", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_serHostMenuItemActionPerformed

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        // Criar Dialog de informações
        // StringBuilder pro HTML não bugar
        StringBuilder sb = new StringBuilder();
        sb.append("<html><b>LUDO DOS CAMPEÕES</b><br>");
        sb.append("Idealizado e programado pelos seguintes cornos:<br><ul>");
        sb.append("<li>Daniel Henrique Serezane Pereira<br>");
        sb.append("<li>Guilherme Silva Batalhoti<br>");
        sb.append("<li>Gustavo Becelli do Nacimento<br>");
        sb.append("</ul>FCT/UNESP - 2023</html>");
        JOptionPane.showMessageDialog(this, sb.toString(), "Sobre", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_sobreMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ajudaMenu;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JMenuItem conectarMenuItem;
    private javax.swing.JMenu conexMenu;
    private javax.swing.JLabel diceLabel;
    private javax.swing.JLabel historicoLabel;
    private javax.swing.JTextPane historicoPane;
    private javax.swing.JScrollPane historicoScrollPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton rollButton;
    private javax.swing.JMenuItem serHostMenuItem;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables
}
